[workspace]
members = ["myorm_macros"]
resolver = "2"

[workspace.package]
edition = "2024"

[package]
name = "myorm"
version = "0.1.0"
edition.workspace = true

[dependencies]
inventory = { version = "0.3.19", default-features = false }
serde = { version = "1.0.217", default-features = false, features = ["derive", "std"] }
serde_json = { version = "1.0.138", default-features = false, features = ["alloc"] }
sha1 = { version = "0.10.6", default-features = false }
tokio-postgres = { version = "0.7.13", default-features = false }

[dependencies.myorm_macros]
path = "myorm_macros"
