WHITESPACE = _{ " " | "\t" | "\r" | "\n" }

Ident = @{ (XID_START ~ XID_CONTINUE*) | ("_" ~ XID_CONTINUE+) }

TableName = { (Ident ~ ".")? ~ Ident }
ColumnTuple = { "(" ~ Ident ~ ("," ~ Ident)* ~ ","? ~ ")" }

NoAction = { "no_action" }
Restrict = { "restrict" }
Cascade = { "cascade" }
SetNull = { "set_null" ~ ColumnTuple }
SetDefault = { "set_default" ~ ColumnTuple }
ReferentialAction = { NoAction | Restrict | Cascade | SetNull | SetDefault }

NullsNotDistinct = { "nulls_not_distinct" }

ContainerSchema = _{ Ident }
ContainerPrimaryKey = _{ ColumnTuple }
ContainerForeignKey = _{ ColumnTuple ~ TableName ~ ColumnTuple ~ ReferentialAction? }
ContainerUnique = _{ ColumnTuple ~ NullsNotDistinct? }

FieldForeignKey = _{ TableName ~ "(" ~ Ident ~ ")" ~ ReferentialAction? }
FieldUnique = _{ NullsNotDistinct? }
